[package]
name = "backup2swift"
version = "0.1.0"
authors = ["Tim Dettrick <t.dettrick@uq.edu.au>"]

[dependencies]
clap = "2.26.2"
curl = "0.4.8"
hex = "0.2.0"
hmac = "0.4.2"
log = "0.3.8"
rand = "0.3"
serde_json = "1.0"
sha-1 = "0.4.1"
stderrlog = "0.2.3"
url = "1.5.1"
